# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode11.4
language: objective-c
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/HapticGenerator.xcworkspace -scheme HapticGenerator_ExampleTests -sdk iphonesimulator -destination 'OS=13.4.1,name=iPhone 8' | xcpretty
