# references:
# * http://www.objc.io/issue-6/travis-ci.html
# * https://github.com/supermarin/xcpretty#usage

osx_image: xcode10
language: objective-c
podfile: Example/Podfile
before_install:
- pod install --project-directory=Example
script:
- set -o pipefail && xcodebuild test -workspace Example/HapticGenerator.xcworkspace -scheme HapticGenerator-Example -sdk iphonesimulator -destination 'OS=12,name=iPhone X's | xcpretty
